SELECT  
       P.[ProductKey]
      ,P.[ProductAlternateKey] as [ProductCode]
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,P.[EnglishProductName] as [ProductName]
      ,PS.[EnglishProductSubcategoryName] as [SubCategory]
      ,PC.[EnglishProductCategoryName] as [ProductCategory]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,P.[Color] as [ProductColor]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,P.[Size] as [ProductSize]
      --,[SizeRange ]
      --,[Weight]
      --,[DaysToManufacture]
      ,[ProductLine]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,[ModelName] as [ProductModelName]
      --,[LargePhoto]
      ,[EnglishDescription] as [ProductDescription]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      --,[StartDate]
      --,[EndDate]
      ,ISNULL (P.[Status], 'Outdated') as [ProductStatus] --If productstatus = mull => replace by "outdated"
  FROM [AdventureWorksDW2019].[dbo].[DimProduct] as P
  LEFT JOIN [AdventureWorksDW2019].[dbo].[DimProductSubcategory] as PS on PS.[ProductSubcategoryKey] = P.[ProductSubcategoryKey]
  LEFT JOIN [AdventureWorksDW2019].[dbo].[DimProductCategory] as PC on PS.[ProductCategoryKey] = PC.[ProductCategoryKey]
  ORDER BY P.ProductKey ASC